name: justllmgrpo
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - git
  - packaging
  - ninja
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - -r requirements.txt
